CC = gcc
CFLAGS = -Wall -pedantic -std=c99
INCLUDES = -Iinclude
BINDIR = bin/
SRCDIR = src/
SOURCE = $(SRCDIR)linkedlist.c $(SRCDIR)stack.c $(SRCDIR)maze.c
PROGNAME = $(BINDIR)run

all:
	$(CC) $(CFLAG) $(SOURCE) $(INCLUDES) -o $(PROGNAME)


